/**
 * Site Configuration
 *
 * This file contains all site-specific settings that can be customized
 * for different niches (Fashion, Fitness, Food, Tech, etc.)
 *
 * GENERATED FILE - Do not edit manually
 * Generated by: Site Generator
 * Generated at: 2025-11-06T13:23:46.717Z
 */

import { getLanguageConfig, type SupportedLanguage } from './languages';

export interface SiteConfig {
  // Basic Site Information
  site: {
    name: string;
    tagline: string;
    description: string;
    url: string;
    wordpressUrl: string;
    language: string;
    locale: string;
  };

  // Brand Identity
  brand: {
    colors: {
      primary: string;
      secondary: string;
      accent: string;
      background: string;
      text: string;
      textSecondary?: string;
    };
    typography: {
      headingFont: string;
      bodyFont: string;
    };
    logo?: {
      text: string;
      subtitle?: string;
    };
  };

  // Content Settings
  content: {
    postsPerPage: number;
    relatedPostsCount: number;
    excerptLength: number;
    featuredImageRatio: string;
    showAuthor: boolean;
    showDate: boolean;
    showCategories: boolean;
    showTags: boolean;
  };

  // Navigation
  navigation: {
    header: Array<{
      label: string;
      href: string;
      external?: boolean;
    }>;
    footer: {
      sections: Array<{
        title: string;
        links: Array<{
          label: string;
          href: string;
          external?: boolean;
        }>;
      }>;
    };
    menuCategories?: Array<{
      name: string;
      slug: string;
    }>;
  };

  // Social Media
  social: {
    pinterest?: string;
    instagram?: string;
    facebook?: string;
    twitter?: string;
    youtube?: string;
    tiktok?: string;
    email?: string;
  };

  // Analytics & Tracking
  analytics: {
    googleAnalytics?: string;
    googleAdsense?: string;
    facebookPixel?: string;
    pinterestTag?: string;
  };

  // Legal Information
  legal: {
    companyName: string;
    contactEmail: string;
    country: string;
    jurisdiction: string;
  };

  // Hero Section (Homepage)
  hero: {
    title: string;
    subtitle: string;
    backgroundImage: string;
    cta?: {
      text: string;
      href: string;
    };
  };

  // Persona / About Page
  persona?: {
    name: string;
    role: string;
    bio: string;
    story: string;
    expertise: string[];
    image?: string;
    quote?: string;
    achievements?: string[];
  };

  // Features / Highlights
  features?: Array<{
    title: string;
    description: string;
    icon?: string;
  }>;

  // Custom Scripts/Code Injection
  customScripts?: {
    headScripts?: string;
    bodyStartScripts?: string;
    bodyEndScripts?: string;
  };

  // SEO Defaults
  seo: {
    titleTemplate: string;
    defaultTitle: string;
    defaultDescription: string;
    twitterHandle?: string;
  };
}

/**
 * Current Site Configuration
 */
export const siteConfig: SiteConfig = {
  site: {
    name: "Lookenly",
    tagline: "Fashion, Beauty & Lifestyle",
    description: "Discover the latest trends in fashion, beauty tips, and lifestyle inspiration.",
    url: process.env.NEXT_PUBLIC_SITE_URL || "https://lookenly.com",
    wordpressUrl: process.env.NEXT_PUBLIC_WORDPRESS_API_URL?.replace('/graphql', '') || "https://wp.lookenly.com",
    language: "en",
    locale: "en_US",
  },

  brand: {
    colors: {
      "primary": "#000000",
      "secondary": "#f5f5f4",
      "accent": "#f59e0b",
      "background": "#fafaf9",
      "text": "#171717"
},
    typography: {
      "headingFont": "Playfair Display",
      "bodyFont": "Montserrat"
},
    logo: {
      text: "LOOKENLY",
      subtitle: "Fashion, Beauty & Lifestyle",
    },
  },

  content: {
    postsPerPage: 12,
    relatedPostsCount: 5,
    excerptLength: 160,
    featuredImageRatio: "3:2",
    showAuthor: true,
    showDate: true,
    showCategories: true,
    showTags: true,
  },

  navigation: {
    header: [
      {
            "label": "Home",
            "href": "/"
      },
      {
            "label": "About",
            "href": "/about"
      }
],
    footer: {
      sections: [
        {
                "title": "Explore",
                "links": [
                        {
                                "label": "Beauty",
                                "href": "/category/beauty"
                        },
                        {
                                "label": "Fashion",
                                "href": "/category/fashion"
                        }
                ]
        },
        {
                "title": "Legal",
                "links": [
                        {
                                "label": "Privacy Policy",
                                "href": "/privacy"
                        },
                        {
                                "label": "Terms of Service",
                                "href": "/terms"
                        },
                        {
                                "label": "Disclaimer",
                                "href": "/disclaimer"
                        }
                ]
        },
        {
                "title": "Follow",
                "links": [
                        {
                                "label": "Pinterest",
                                "href": "https://pinterest.com/lookenlyFashion/",
                                "external": true
                        }
                ]
        }
],
    },
    menuCategories: [
      {
            "name": "Beauty",
            "slug": "beauty"
      },
      {
            "name": "Fashion",
            "slug": "fashion"
      }
],
  },

  social: {
    pinterest: "https://pinterest.com/lookenlyFashion/",
    instagram: "",
    facebook: "",
    twitter: "",
    youtube: "",
    tiktok: "",
    email: "",
  },

  analytics: {
    // googleAnalytics: "",
    // googleAdsense: "",
  },

  customScripts: {
    headScripts: `<script defer data-domain="lookenly.com" src="https://stats.tripleadigital.de/js/script.js"></script>`,
    // bodyStartScripts: "",
    // bodyEndScripts: "",
  },

  legal: {
    companyName: "Triple A Digital",
    contactEmail: "hey@lookenly.com",
    country: "Germany",
    jurisdiction: "Germany",
  },

  hero: {
    "title": "Discover Your Style",
    "subtitle": "Fashion, Beauty & Lifestyle Inspiration",
    "backgroundImage": "/images/hero-bg.jpg",
    "cta": {
        "text": "Explore Now",
        "href": "#categories"
    }
},

  seo: {
    titleTemplate: "%s | Lookenly",
    defaultTitle: "Lookenly - Fashion, Beauty & Lifestyle",
    defaultDescription: "Discover the latest trends in fashion, beauty tips, and lifestyle inspiration.",
  },
};

/**
 * Helper function to get nested config values safely
 */
export function getConfigValue<T>(path: string, defaultValue?: T): T | undefined {
  const keys = path.split('.');
  let value: any = siteConfig;

  for (const key of keys) {
    if (value && typeof value === 'object' && key in value) {
      value = value[key];
    } else {
      return defaultValue;
    }
  }

  return value as T;
}

/**
 * Get language configuration for current site
 */
export function getLanguage() {
  const langCode = siteConfig.site.language as SupportedLanguage;
  return getLanguageConfig(langCode);
}

/**
 * Get translated UI strings
 */
export function t() {
  return getLanguage().ui;
}
